# Generated by Django 5.0.1 on 2024-02-04 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=1000)),
                ('priority', models.IntegerField()),
                ('dtime', models.DateTimeField(default=datetime.datetime(2024, 2, 5, 6, 44, 37, 909149), verbose_name='Timestamp')),
                ('phash', models.CharField(max_length=4, verbose_name='Hash')),
                ('red', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
            ],
        ),
    ]
